# Generated by Django 3.2.6 on 2022-05-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghs_fk',
            name='title',
            field=models.CharField(default='Knowledge health', editable=False, max_length=50),
        ),
    ]
