# Generated by Django 4.0.6 on 2022-08-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0002_ghs_fk_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='many_actions',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='sys_time',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='unders_sys',
        ),
    ]
