# Generated by Django 4.0.6 on 2022-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0003_remove_evaluatechoices_many_actions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_url', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now=True)),
                ('image_url', models.CharField(max_length=300)),
                ('subtype', models.CharField(max_length=50)),
            ],
        ),
    ]
