# Generated by Django 4.0.6 on 2022-08-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0004_climatenews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatenews',
            options={'ordering': ['id'], 'verbose_name': 'ClimateNews'},
        ),
        migrations.AlterModelTable(
            name='climatenews',
            table='ClimateNews',
        ),
    ]
