# Generated by Django 4.0.6 on 2022-08-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0005_alter_climatenews_options_alter_climatenews_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatenews',
            options={},
        ),
        migrations.AlterModelTable(
            name='climatenews',
            table=None,
        ),
    ]
