# Generated by Django 4.0.6 on 2022-08-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0006_alter_climatenews_options_alter_climatenews_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatenews',
            options={'ordering': ['id'], 'verbose_name': 'ClimateNews'},
        ),
        migrations.RemoveField(
            model_name='climatenews',
            name='date',
        ),
        migrations.AlterModelTable(
            name='climatenews',
            table='ClimateNews',
        ),
    ]
