# Generated by Django 4.0.6 on 2022-08-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0007_alter_climatenews_options_remove_climatenews_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatenews',
            options={},
        ),
        migrations.AlterModelTable(
            name='climatenews',
            table=None,
        ),
    ]
