# Generated by Django 4.0.6 on 2022-08-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0008_alter_climatenews_options_alter_climatenews_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatenews',
            options={'ordering': [], 'verbose_name': 'ClimateNews'},
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='article_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='image_url',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='subcategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='text',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterModelTable(
            name='climatenews',
            table='ClimateNews',
        ),
    ]
