# Generated by Django 4.0.6 on 2022-08-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0009_alter_climatenews_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='choice_overwhelming',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='easy_choice',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='many_to_choose',
        ),
    ]
