# Generated by Django 4.0.6 on 2022-08-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0010_remove_evaluatechoices_choice_overwhelming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='know_many',
        ),
    ]
