# Generated by Django 4.0.6 on 2022-08-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0011_remove_evaluatechoices_know_many'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluatechoices',
            old_name='liked_recipes',
            new_name='liked_news',
        ),
    ]
