# Generated by Django 4.0.6 on 2022-08-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0012_rename_liked_recipes_evaluatechoices_liked_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices',
            name='liked_news',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='liked_news'),
        ),
    ]
