# Generated by Django 4.0.6 on 2022-08-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0014_remove_evaluatechoices_prepare_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='Trust_news',
        ),
        migrations.AddField(
            model_name='evaluatechoices',
            name='prepare_recipes',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='prepare_recipes'),
        ),
    ]
