# Generated by Django 4.1 on 2022-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0015_remove_evaluatechoices_trust_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatenews',
            name='author',
            field=models.CharField(default='Some String', max_length=100),
        ),
        migrations.AddField(
            model_name='climatenews',
            name='author_bio',
            field=models.CharField(default='Some String', max_length=1000),
        ),
        migrations.AddField(
            model_name='climatenews',
            name='date',
            field=models.CharField(default='Some String', max_length=100),
        ),
        migrations.AddField(
            model_name='climatenews',
            name='image_caption',
            field=models.CharField(default='Some String', max_length=100),
        ),
        migrations.AddField(
            model_name='climatenews',
            name='time',
            field=models.CharField(default='Some String', max_length=100),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='article_url',
            field=models.CharField(default='Some String', max_length=500),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='category',
            field=models.CharField(default='Some String', max_length=50),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='image_url',
            field=models.CharField(default='Some String', max_length=500),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='subcategory',
            field=models.CharField(default='Some String', max_length=100),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='subtype',
            field=models.CharField(default='Some String', max_length=100),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='text',
            field=models.CharField(default='Some String', max_length=4000),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='title',
            field=models.CharField(default='Some String', max_length=500),
        ),
        migrations.AlterField(
            model_name='climatenews',
            name='type',
            field=models.CharField(default='Some String', max_length=50),
        ),
    ]
