# Generated by Django 4.1 on 2022-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0017_evaluatechoices2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices2',
            name='fit_preference',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='fit_preference2'),
        ),
        migrations.AlterField(
            model_name='evaluatechoices2',
            name='liked_news',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='liked_news2'),
        ),
        migrations.AlterField(
            model_name='evaluatechoices2',
            name='prepare_recipes',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='prepare_recipes2'),
        ),
        migrations.AlterField(
            model_name='evaluatechoices2',
            name='recommend_recipe',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='recommend_recipe2'),
        ),
    ]
