# Generated by Django 4.1 on 2022-08-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0019_evaluatechoices3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices3',
            name='recommend_recipe',
        ),
        migrations.AddField(
            model_name='evaluatechoices3',
            name='recommend_news',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='recommend_news3'),
        ),
    ]
