# Generated by Django 4.1 on 2022-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0020_remove_evaluatechoices3_recommend_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices3',
            name='prepare_recipes',
        ),
        migrations.AddField(
            model_name='evaluatechoices3',
            name='trust_news',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='trust_news3'),
        ),
    ]
