# Generated by Django 4.1 on 2022-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0021_remove_evaluatechoices3_prepare_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='prepare_recipes',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='recommend_recipe',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices2',
            name='prepare_recipes',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices2',
            name='recommend_recipe',
        ),
        migrations.AddField(
            model_name='evaluatechoices',
            name='recommend_news',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='recommend_news'),
        ),
        migrations.AddField(
            model_name='evaluatechoices',
            name='trust_news',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='trust_news'),
        ),
        migrations.AddField(
            model_name='evaluatechoices2',
            name='recommend_news',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='recommend_news2'),
        ),
        migrations.AddField(
            model_name='evaluatechoices2',
            name='trust_news',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='trust_news2'),
        ),
    ]
