# Generated by Django 4.1 on 2022-08-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0022_remove_evaluatechoices_prepare_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices',
            name='liked_news',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Little Content', 'Little Content'), ('Some Content', 'Some Content'), ('Most Content', 'Most Content'), ('All', 'All')], default=None, max_length=100, verbose_name='liked_news'),
        ),
        migrations.AlterField(
            model_name='evaluatechoices2',
            name='liked_news',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Little Content', 'Little Content'), ('Some Content', 'Some Content'), ('Most Content', 'Most Content'), ('All', 'All')], default=None, max_length=100, verbose_name='liked_news2'),
        ),
        migrations.AlterField(
            model_name='evaluatechoices3',
            name='liked_news',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Little Content', 'Little Content'), ('Some Content', 'Some Content'), ('Most Content', 'Most Content'), ('All', 'All')], default=None, max_length=100, verbose_name='liked_news3'),
        ),
        migrations.CreateModel(
            name='EvaluateChoices4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='EvaluateChoices4', editable=False, max_length=50)),
                ('liked_news', models.CharField(choices=[('Not at all', 'Not at all'), ('Little Content', 'Little Content'), ('Some Content', 'Some Content'), ('Most Content', 'Most Content'), ('All', 'All')], default=None, max_length=100, verbose_name='liked_news4')),
                ('trust_news', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='trust_news4')),
                ('fit_preference', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='fit_preference4')),
                ('recommend_news', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='recommend_news4')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(default=None, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labels_Nudges.personal_info')),
            ],
            options={
                'verbose_name': 'EvaluateChoices4',
                'db_table': 'EvaluateChoices4',
                'ordering': ['id'],
            },
        ),
    ]
