# Generated by Django 4.1 on 2022-08-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0023_alter_evaluatechoices_liked_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices4',
            name='liked_news',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='liked_news4'),
        ),
    ]
