# Generated by Django 4.1 on 2022-08-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0024_alter_evaluatechoices4_liked_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices4',
            name='liked_news',
            field=models.CharField(choices=[('Not at all', 'Not at all'), ('Little Content', 'Little Content'), ('Some Content', 'Some Content'), ('Most Content', 'Most Content'), ('All', 'All')], default=None, max_length=100, verbose_name='liked_news3'),
        ),
    ]
