# Generated by Django 4.1 on 2022-08-31 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0027_evaluatechoices5'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluateChoices6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='EvaluateChoices6', editable=False, max_length=50)),
                ('liked_news', models.CharField(choices=[('Not at all', 'Not at all'), ('Little Content', 'Little Content'), ('Some Content', 'Some Content'), ('Most Content', 'Most Content'), ('All', 'All')], default=None, max_length=100, verbose_name='liked_news6')),
                ('trust_news', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='trust_news6')),
                ('fit_preference', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='fit_preference6')),
                ('recommend_news', models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='recommend_news6')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(default=None, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labels_Nudges.personal_info')),
            ],
            options={
                'verbose_name': 'EvaluateChoices6',
                'db_table': 'EvaluateChoices6',
                'ordering': ['id'],
            },
        ),
    ]
