# Generated by Django 4.1 on 2022-09-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0033_evaluatechoices_attention_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='attention_check',
        ),
    ]
