# Generated by Django 4.1 on 2022-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0034_remove_evaluatechoices_attention_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatechoices',
            name='many_to_choose',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='many_to_choose'),
        ),
    ]
