# Generated by Django 4.1 on 2022-09-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0035_evaluatechoices_many_to_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatechoices8',
            name='many_to_choose',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('Brown', 'Brown')], default=None, max_length=100, verbose_name='many_to_choose'),
        ),
        migrations.AlterField(
            model_name='evaluatechoices',
            name='many_to_choose',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('Brown', 'Brown')], default=None, max_length=100, verbose_name='many_to_choose'),
        ),
    ]
