# Generated by Django 4.1 on 2022-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0036_evaluatechoices8_many_to_choose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatechoices',
            name='news_id',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
