# Generated by Django 4.1 on 2022-09-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0037_evaluatechoices_news_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='news_id',
        ),
    ]
