# Generated by Django 4.1 on 2022-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0038_remove_evaluatechoices_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatechoices',
            name='news_id',
            field=models.IntegerField(default=0),
        ),
    ]
