# Generated by Django 4.1 on 2022-09-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0039_evaluatechoices_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices',
            name='news_id',
            field=models.IntegerField(default=None),
        ),
    ]
