# Generated by Django 4.1 on 2022-09-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0040_alter_evaluatechoices_news_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluatechoices',
            old_name='news_id',
            new_name='newsID',
        ),
    ]
