# Generated by Django 4.1 on 2022-09-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0041_rename_news_id_evaluatechoices_newsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='newsID',
        ),
    ]
