# Generated by Django 4.1 on 2022-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0042_remove_evaluatechoices_newsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices',
            name='created',
            field=models.IntegerField(default=None),
        ),
    ]
