# Generated by Django 4.1 on 2022-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0043_alter_evaluatechoices_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices',
            name='created',
            field=models.CharField(default='1', max_length=1000),
        ),
        migrations.AlterField(
            model_name='evaluatechoices',
            name='fit_preference',
            field=models.CharField(choices=[('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default='Some String', max_length=100, verbose_name='fit_preference'),
        ),
        migrations.AlterField(
            model_name='evaluatechoices',
            name='session_id',
            field=models.CharField(default='Some String', max_length=100),
        ),
    ]
