# Generated by Django 4.1 on 2022-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0045_alter_evaluatechoices_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices',
            name='created',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
