# Generated by Django 4.1 on 2022-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0046_alter_evaluatechoices_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices2',
            name='created',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
