# Generated by Django 4.1 on 2022-09-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0048_alter_evaluatechoices3_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatechoices10',
            name='created',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='evaluatechoices4',
            name='created',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='evaluatechoices5',
            name='created',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='evaluatechoices6',
            name='created',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='evaluatechoices7',
            name='created',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='evaluatechoices8',
            name='created',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='evaluatechoices9',
            name='created',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
